//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EigMedicoes.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EIG_Particionamento_ContratosEnergia
    {
        public int ID_Unidade { get; set; }
        public string Identificador { get; set; }
        public System.DateTime Inicio { get; set; }
        public System.DateTime Fim { get; set; }
        public string Ponta { get; set; }
        public Nullable<decimal> Representatividade_Porcentagem { get; set; }
        public Nullable<decimal> Representatividade_MWh { get; set; }
        public Nullable<decimal> Montante_Exercido { get; set; }
        public Nullable<int> Particionamento_Automatico { get; set; }
    }
}
