//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EigMedicoes.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EIGMedicao_View_Cadastro
    {
        public int Codigo_de_Cadastro { get; set; }
        public string Grupo { get; set; }
        public string Nome { get; set; }
        public string Tipo { get; set; }
    }
}
