//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EigMedicoes.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EIGMedicao_Import_Stage2
    {
        public int ID { get; set; }
        public string Agente { get; set; }
        public string Ponto___Grupo { get; set; }
        public string Data { get; set; }
        public string Hora { get; set; }
        public string Energia_Ativa_De_Consumo { get; set; }
        public string Energia_Ativa_De_Geração { get; set; }
        public string Qualidade { get; set; }
        public string Origem { get; set; }
    }
}
