//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EigMedicoes.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EIGMedicao_View_Medicoes
    {
        public string Ponto { get; set; }
        public System.DateTime Periodo { get; set; }
        public decimal Consumo { get; set; }
        public decimal Geracao { get; set; }
        public bool Consistido { get; set; }
        public bool Manual { get; set; }
    }
}
