//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EigMedicoes.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EIGMedicao_View_Agente
    {
        public int ID_Unidade { get; set; }
        public int ID_Cadastro { get; set; }
        public Nullable<int> CD_AGEN_SCDD { get; set; }
        public string SG_AGEN_SCDD { get; set; }
        public string Tipo { get; set; }
        public string Unidade { get; set; }
        public string Agente { get; set; }
        public Nullable<decimal> Fator_Perda { get; set; }
    }
}
