//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EigMedicoes.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EIGMedicao_View_Contratos3
    {
        public Nullable<int> ID_UNIDADE { get; set; }
        public string IDENTIFICACAO_UNIDADE { get; set; }
        public System.DateTime INICIO { get; set; }
        public System.DateTime FIM { get; set; }
        public Nullable<decimal> MONTANTE_CONTRATADO { get; set; }
        public Nullable<decimal> FLEX_MIN_CONTRATADO { get; set; }
        public Nullable<decimal> FLEX_MAX_CONTRATADO { get; set; }
        public Nullable<decimal> MONTANTE_EXERCIDO { get; set; }
        public Nullable<decimal> MONTANTE { get; set; }
    }
}
